# FROM ubuntu:16.04

# RUN apt-get update
# RUN    apt-get install -y git
# RUN docker-php-ext-install pdo pdo_mysql mysqli
# RUN a2enmod rewrite
#Install Composer
# RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# RUN php composer-setup.php --install-dir=. --filename=composer
# RUN mv composer /usr/local/bin/
# COPY loris/ /var/www/html/
# EXPOSE 80

FROM php:7.2-apache

# Install dependencies.
# g++ (v. 5.4) does not work: https://github.com/tensorflow/tensorflow/issues/13308
RUN apt-get update \
    && apt-get install -y  \
        apt-utils --no-install-recommends \
        zip \
        curl \
        wget \
        python-software-properties \
        software-properties-common \
        mysql-client \
        language-pack-en-base 

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer



# Creating a User for LORIS
RUN useradd -U -m -G sudo -s /bin/bash lorisadmin
RUN echo lorisadmin:12345678 | chpasswd
RUN su - lorisadmin

COPY ./loris /var/www/loris
RUN chown -R lorisadmin.lorisadmin /var/www/loris

WORKDIR /var/www/loris

RUN composer install


#RUN service apache2 restart


WORKDIR /var/www/loris/tools
RUN bash install_aueb.sh

RUN a2enmod rewrite
RUN a2ensite loris
RUN chmod 775 /var/www/loris/project/

#RUN service apache2 reload

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
#&& \ a2enconf fqdn

#RUN service apache2 restart

#donwload composer
WORKDIR /var/www/loris



# Select php7.2 as default
#RUN update-alternatives --set php /usr/bin/php7.2


# Nodejs installation
RUN curl -sL https://deb.nodesource.com/setup_8.x > install_node.sh
RUN bash install_node.sh
RUN apt-get install -y nodejs

#WORKDIR /var/www/loris
#RUN make

COPY other_files/config.xml /var/www/loris/project/config.xml



EXPOSE 80

ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
